amat_majors_pool = {
    'AMAT 115': {'course_title': 'Introduction to Mathematical Decision Theory',
                 'units': 3,
                 'prerequisites': ['AMAT 110', 'MATH 181'],
                 'season': [2]},
    'AMAT 160': {'course_title': 'Linear Programming',
                 'units': 3,
                 'prerequisites': ['AMAT 110', 'AMAT 105'],
                 'season': [1]},
    'AMAT 161': {'course_title': 'Non-Linear Programming',
                 'units': 3,
                 'prerequisites': ['AMAT 110', 'AMAT 105'],
                 'season': [2]},
    'AMAT 162': {'course_title': 'Integer and Dynamic Programming',
                 'units': 2,
                 'prerequisites': ['AMAT 160'],
                 'season': [2]},
    'AMAT 163': {'course_title': 'Metaheuristics',
                 'units': 3,
                 'prerequisites': ['AMAT 110'],
                 'season': [1]},
    'AMAT 167': {'course_title': 'Mathematical Models in Operations Research I',
                 'units': 3,
                 'prerequisites': ['AMAT 110'],
                 'season': [1]},
    'AMAT 168': {'course_title': 'Mathematical Models in Operations Research II',
                 'units': 3,
                 'prerequisites': ['AMAT 160'],
                 'season': [2]},
    'AMAT 171': {'course_title': 'Life Insurance Mathematics I',
                 'units': 3,
                 'prerequisites': ['AMAT 170'],
                 'season': [1]},
    'AMAT 172': {'course_title': 'Life Insurance Mathematics II',
                 'units': 3,
                 'prerequisites': ['AMAT 171'],
                 'season': [1]},
    'AMAT 174': {'course_title': 'Measurement of Mortality',
                 'units': 3,
                 'prerequisites': [],
                 'season': []},
    'AMAT 176': {'course_title': 'Actuarial Science',
                 'units': 3,
                 'prerequisites': [],
                 'season': []},
    'AMAT 177': {'course_title': 'Introduction to Mathematical Finance',
                 'units': 3,
                 'prerequisites': ['AMAT 170', 'MATH 181'],
                 'season': [2]},
    'AMAT 178': {'course_title': 'Stochastics Calculus for Finance',
                 'units': 3,
                 'prerequisites': ['AMAT 177', 'AMAT 182'],
                 'season': [1]},
    'AMAT 180': {'course_title': 'Introduction to Biomathematics',
                 'units': 3,
                 'prerequisites': ['MATH 38', 'AMAT 105'],
                 'season': [2]},
    'AMAT 191': {'course_title': 'Special Topics',
                 'units': 3,
                 'prerequisites': ['COI'],
                 'season': [1]},
    'MATH 111': {'course_title': 'Modern Algebra I',
                 'units': 3,
                 'prerequisites': ['MATH 101'],
                 'season': [1,2]},
    'MATH 115': {'course_title': 'Introduction to Coding Theory and Cryptography',
                 'units': 3,
                 'prerequisites': ['MATH 111'],
                 'season': [2]},
    'MATH 141': {'course_title': 'Introductory Combinatorics',
                 'units': 3,
                 'prerequisites': ['MATH 38', 'MATH 101'],
                 'season': [2]},
    'MATH 143': {'course_title': 'Graph Theory',
                 'units': 3,
                 'prerequisites': ['MATH 101'],
                 'season': [1]},
    'MATH 152': {'course_title': 'Partial Differential Equations',
                 'units': 3,
                 'prerequisites': ['MATH 151'],
                 'season': [2]},
    'MATH 182': {'course_title': 'Introduction to Stochastic Processes',
                 'units': 3,
                 'prerequisites': ['MATH 181'],
                 'season': [2]}, 
}