math_majors_pool = {
    'MATH 112': {'course_title': 'Modern Algebra II',
                 'units': 3,
                 'prerequisites': ['MATH 111'],
                 'season': [2]},
    'MATH 115': {'course_title': 'Introduction to Coding Theory and Cryptography',
                 'units': 3,
                 'prerequisites': ['MATH 111'],
                 'season': [2]},
    'MATH 143': {'course_title': 'Graph Theory',
                 'units': 3,
                 'prerequisites': ['MATH 101'],
                 'season': [1]},
    'MATH 152': {'course_title': 'Partial Differential Equations',
                 'units': 3,
                 'prerequisites': ['MATH 151'],
                 'season': [2]},
    'MATH 156': {'course_title': 'Advanced Calculus II',
                 'units': 3,
                 'prerequisites': ['MATH 155'],
                 'season': [2]},
    'MATH 160': {'course_title': 'Vector Analysis',
                 'units': 3,
                 'prerequisites': ['MATH 38'],
                 'season': [2]},
    'MATH 166': {'course_title': 'Complex Analysis II',
                 'units': 3,
                 'prerequisites': ['MATH 165'],
                 'season': [2]},
    'MATH 170': {'course_title': 'Finite Differences',
                 'units': 3,
                 'prerequisites': ['MATH 38'],
                 'season': [1]},
    'MATH 174': {'course_title': 'Numerical Analysis I',
                 'units': 3,
                 'prerequisites': ['MATH 38, AMAT 152'],
                 'season': [1]},
    'MATH 175': {'course_title': 'Numerical Analysis II',
                 'units': 3,
                 'prerequisites': ['MATH 174'],
                 'season': [2]},
    'MATH 182': {'course_title': 'Introduction to Stochastic Processes',
                 'units': 3,
                 'prerequisites': ['MATH 181'],
                 'season': [2]},
    'MATH 191': {'course_title': 'Special Topics',
                 'units': 3,
                 'prerequisites': ['COI'],
                 'season': [1]},
}